# Generated by Django 5.0.1 on 2024-02-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="enquiry",
            field=models.CharField(max_length=1000),
        ),
    ]
