# Generated by Django 5.0.1 on 2024-02-06 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_contactus_enquiry"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactUs",
            new_name="ContactUsNow",
        ),
    ]
